### ISSUE TITLE
export CreateProxy and ExtractVuexModule as functions

### ISSUE THREAD

**Issue by IceSentry** [michaelolof/vuex-class-component#25]
Currently to create a proxy or to extract a module you need to type the class 2 times. From looking at the code I believe it would be fairly easy to export `createProxy(store, moduleClass)` and `exportVuexModule(moduleClass)` as stand alone functions and therefore reducing verbosity a little bit.

I'm open to doing a PR if this is a feature you want.

The end result would be :

```javascript
 import {createProxy, extractVuexModule} from 'vuex-class-component'

  export const store = new Vuex.Store({
    modules: {
      user: extractVuexModule( UserStore ),
      pages: extractVuexModule( PagesStore ),
      story: extractVuexModule( StoryStore ),
    }
  })

  export const vxm = {
    user: createProxy( store, UserStore ),
    pages: createProxy( store, PagesStore ),
    story: createProxy( store, StoryStore ),
  }
```

There might even be a way to use TS generics to achieve similar results. It could also use partial application and currying to pass the store only once to the `createProxy` function. I also believe this could all remain completely type safe if done correctly.

**Comment by michaelolof** [comment]
Hello @IceSentry 
Sorry for the late reply.

I understand your concern. The need to type the class two times is also something that bugs me.
But at this point, We need to think of maintaining a stable api.

Also the usage of static functions rather than external functions was intentional.
We wanted something users could easily recognise, we felt this was easy to do using the static functions especially with intellisense support.

I intend to look into this though, so I will keep this issue open for now.

**Comment by michaelolof** [comment]
Added in new API
